### ISSUE TITLE
Integrate with either

### ISSUE THREAD

**Issue by Stebalien** [rust-itertools/itertools#129]
Related to https://internals.rust-lang.org/t/where-would-a-join-that-writes-to-some-impl-write-go/3521/8 and rust-lang/rust#34143.

It would be nice if itertools integrated with [either](https://github.com/bluss/either) to provide:
- `left`, `right` -- Return iterators mapping over `Either::Left`/`Either::Right`.
- `interleave_either`, `interleave_either_shortest`, `intersperse_either`, and `chain_either` -- Same as the existing adapters but these would work with distinct types.

If the above rust PR were merged, it would be possible to write: `some_string.extend(items.intersperse_either(", "))`.

**Comment by Stebalien** [comment]
Alternatively, one could name these functions `interleave_{left,right}` etc. to allow for more control.

**Comment by bluss** [comment]
Interesting idea. Either is certainly Iterator-related, it exists partly because I didn't want to reimplement the two-case iterator many times.

There's some overlap between the crates. itertools::Partition could just have been the Either enum. So for that reason it seems like a good idea. It's also a very small crate to add as a dependency. It has the risk of thrusting the either crate and type into a lot more rusties' hands, I wonder what they will think.

The left, right iterators don't seem necessary, since the .left(), .right() methods return options that are iterable. So that functionality is available already through composition.

The extend line would not actually be possible would it, since String::extend doesn't use any generics or `AsRef<str>` or so, it needs an iterator of &str.

**Comment by Stebalien** [comment]
> The extend line would not actually be possible would it, since String::extend doesn't use any generics or AsRef<str> or so, it needs an iterator of &str.

See rust-lang/rust#34143 (whether or not this gets accepted, or even should be accepted, is another issue).


> The left, right iterators don't seem necessary, since the .left(), .right() methods return options that are iterable. So that functionality is available already through composition.

I'm not sure I follow here. I'm suggesting a helper function and type equivalent to `iterator.map(Either::{left, right})`. This is mostly to get namable types (i.e., avoid functions in types).

**Comment by bluss** [comment]
It sounds like you mean either `Either::Left` as a function (that already exists) or the function `Either::left composed with .unwrap()` ?

**Comment by Stebalien** [comment]
I mean `Either::Left` as a function. Basically, `first.chain_either(second)` would be shorthand for `first.left().chain(second.right()).

**Comment by bluss** [comment]
aha. So `.left()` would be an iterator adaptor equivalent to `.map(Either::Left)`

**Comment by Stebalien** [comment]
...caps (yes).

**Comment by bluss** [comment]
The breaking change part of this is going to be done for 0.5. That's changing out Partition for the Either enum

**Comment by Centril** [comment]
I'm personally partial to / and biased in favor of the `frunk` crate which is more general in that it provides support for "anonymous coproducts" with arbitrary many variants.

**Comment by bluss** [comment]
@Centril sounds interesting, but frunk will not be a dependency of itertools, so we can't do so much with it.
