### ISSUE TITLE
Feature: add circular_tuple_windows

### ISSUE THREAD

**Issue by ed-bassett** [rust-itertools/itertools#349]
The `tuple_windows` function is very useful, but I've found myself using something like the following quite often — it's very useful when processing anything circular in nature, but represented as a Vec (or anything `iter`):
```
something.iter().cycle().tuple_windows().take(self.len())
```

Where `tuple_windows::<(_,_,_)>` for [1,2,3,4] would iterate through `(1,2,3)` & `(2,3,4)`, `circular_tuple_windows::<(_,_,_)>` would iterate through `(1,2,3)`, `(2,3,4)`, `(3,4,1)` & `(4,1,2)`, meaning that every element would be iterated through, having access to the previous and next elements in a circular structure.

I tried to add just for my project, but I think I would need to use `itertools::tuple_impl::TupleCollect`, which is private. But I figured it would likely be useful for other too, so thought I'd suggest the feature.

**Comment by MatejKafka** [comment]
I don't think this should be implemented with `cycle()`, because it requires the iterator to be clonable, which is imo excessive. Storing
the first `n - 1` items in a buffer (which requires only that the iterated items are clonable, instead of the iterator itself) seems to me like a better solution.
