### ISSUE TITLE
Feature request: arg_min and arg_max

### ISSUE THREAD

**Issue by tspiteri** [rust-itertools/itertools#410]
Currently there is no function to find the index of the minimum or the maximum (somehow analogous to C++ [min_element](https://en.cppreference.com/w/cpp/algorithm/min_element) and [max_element](https://en.cppreference.com/w/cpp/algorithm/max_element)).

In my project I ended up writing `arg_max`, `arg_max_by_key`, `arg_max_by`, `arg_min`, `arg_min_by_key`, `arg_min_by`.

Would a PR adding these be accepted? I do think `arg_max` is maths terminology, not iterator terminology, so I think something like `fn max_position(&mut self) -> Option<(usize, Self::Item)>` would be more consistent with for example [`find_position`](https://docs.rs/itertools/0.8.2/itertools/trait.Itertools.html#method.find_position). My vote would be `{max,min}_position{,_by_key,_by}` for a total of six methods, each returning `Option<(usize, Self::Item)>`.

**Comment by phimuemue** [comment]
Hi there. Sounds reasonable to me.

When we already touch this: Should we implement all the position-returning functions in terms of `enumerate`?

**Comment by jswrenn** [comment]
> Would a PR adding these be accepted?

Yes! Unless the implementations turn out to be non-trivial, it's fine to just provide doc tests for these.

For naming, let's use `position` as a prefix (since it's the position of the min/max element, not the minimum or maximum position); e.g.:  `position_min`, `position_min_by` and `position_min_by_key`.

In the interest of consistency with [`Itertools::minmax`](https://docs.rs/itertools/0.8.2/itertools/trait.Itertools.html#method.minmax), [`Itertools::minmax_by`](https://docs.rs/itertools/0.8.2/itertools/trait.Itertools.html#method.minmax_by) and [`Itertools::minmax_by_key`](https://docs.rs/itertools/0.8.2/itertools/trait.Itertools.html#method.minmax_by_key), what do you think about introducing `position_minmax`, `position_minmax_by` and `position_minmax_by_key`, that all produce <code><a href="https://docs.rs/itertools/0.8.2/itertools/enum.MinMaxResult.html">MinMaxResult</a>&lt;usize&gt;</code>?

> Should we implement all the position-returning functions in terms of enumerate?

Yes, the `arg_{min,max}[_by][_key]` sextet should be implemented with [`Iterator::enumerate`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.enumerate) and <code>Iterator::{<a href="https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.min_by">min</a>,<a href="https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.max_by">max</a>}_by</code>.

The `arg_minmax` trio use should [`Iterator::enumerate`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.enumerate) with [`Itertools::minmax_by`](https://docs.rs/itertools/0.8.2/itertools/trait.Itertools.html#method.minmax_by).

**Comment by tspiteri** [comment]
> > Would a PR adding these be accepted?
> 
> Yes! Unless the implementations turn out to be non-trivial, it's fine to just provide doc tests for these.

I'm working on it! The implementations are pretty simple using `enumerate`.

> For naming, let's use `position` as a prefix (since it's the position of the min/max element, not the minimum or maximum position); e.g.: `position_min`, `position_min_by` and `position_min_by_key`.

Agreed.

> In the interest of consistency with [`Itertools::minmax`](https://docs.rs/itertools/0.8.2/itertools/trait.Itertools.html#method.minmax), [`Itertools::minmax_by`](https://docs.rs/itertools/0.8.2/itertools/trait.Itertools.html#method.minmax_by) and [`Itertools::minmax_by_key`](https://docs.rs/itertools/0.8.2/itertools/trait.Itertools.html#method.minmax_by_key), what do you think about introducing `position_minmax`, `position_minmax_by` and `position_minmax_by_key`, that all produce `[MinMaxResult](https://docs.rs/itertools/0.8.2/itertools/enum.MinMaxResult.html)<usize>`?

Sounds good, I'll include them.

**Comment by orlp** [comment]
I'm just here to say that I came to the issues section precisely to suggest this, I think it's sorely missing from itertools as it's a very common operation.
