### ISSUE TITLE
unique_by: Pick last instead of first match

### ISSUE THREAD

**Issue by hce** [rust-itertools/itertools#446]
I need to extract the last entry of a day. But then sort in ascending order. So what I do is this:

    ...
    .iter()
    .sorted_by(descending order)
    .unique_by(|item| item.day)
    .sorted_by(ascending order)

Would be nice to not having to sort twice here but instead being able to tell unique_by to throw away previous matches rather than all but the first match. :)

**Comment by phimuemue** [comment]
If I'm not mistaken, you could use `coalesce`: itertools::Itertools - Rust.

| 
| 
|  | 
itertools::Itertools - Rust

API documentation for the Rust `Itertools` trait in crate `itertools`.
 |

 |

 |


There you can provide a function whose result `Ok(combined)` can choose itself if it wants to keep the first or last element.





    Am Donnerstag, 4. Juni 2020, 09:58:58 MESZ hat Hans-Christian Esperer <notifications@github.com> Folgendes geschrieben:  
 
 


I need to extract the last entry of a day. But then sort in ascending order. So what I do is this:
...
.iter()
.sorted_by(descending order)
.unique_by(|item| item.day)
.sorted_by(ascending order)

Would be nice to not having to sort twice here but instead being able to tell unique_by to throw away previous matches rather than all but the first match. :)

**Comment by hce** [comment]
Good point, that should work; thanks!
