### ISSUE TITLE
Feature Request: `zip_pad_with_default`

### ISSUE THREAD

**Issue by abrassel** [rust-itertools/itertools#537]
When trying to zip over two iterators of unequal lengths, `zip_longest` is very useful for the case in which one doesn't exist.  
When trying to do zip longest, but the underlying items implement `Default`, it could be useful to have a version of `zip_longest` that pads the shorter iterator with `Item::default()`.

**Comment by scottmcm** [comment]
I don't think a new iterator adapter is the best choice here, since that's a relatively heavy and non-orthogonal addition.

The item type for `zip_longest` is `EitherOrBoth`, though, so maybe add some methods on there to make things easier?

As a sketch,
```
impl<T:Default> impl EitherOrBoth<T> {
    fn or_default(self) -> (T, T) { ... }
}
```

Then `.zip_pad_with_default()` could be done as just `.zip_longest().map(|x| x.or_default())`.

(Dunno what the best name for the method would be.  I'm inspired here by https://docs.rs/itertools/0.9.0/itertools/enum.MinMaxResult.html#method.into_option)

**Comment by abrassel** [comment]
That looks great to me!  I've not contributed to an open source project before - at this point do I submit a pull request?

**Comment by phimuemue** [comment]
> That looks great to me!  I've not contributed to an open source project before - at this point do I submit a pull request?

I think you could give it a try.

**Comment by jswrenn** [comment]
Please do! I'd be happy to merge this.

**Comment by abrassel** [comment]
@jswrenn Done!
