### ISSUE TITLE
Missing Inline Attribute Question

### ISSUE THREAD

**Issue by errantmind** [rust-itertools/itertools#604]
Hello, I was looking through the source code and there appears to be missing inline attributes in several places. For example, looking at the Interleave adapter, there are many functions without the `inline` attribute. Is this intentional and, if so, why?

**Comment by jswrenn** [comment]
I don't think it's intentional. I also wonder if it even matters, since all of the functions/methods in this crate are generic.

**Comment by scottmcm** [comment]
The inline attribute does two things:

1. Makes LLVM slightly more willing to inline it
    - This is actually the less important behaviour, as LLVM will happily inline things that don't have this attribute, when it thinks inlining is a good idea and it has the information needed to do so.  In fact, it'll even inline things with `#[inline(never)]` in certain situations.
2. Puts the MIR of the function into the rlib, so that it can be put in the codegen unit with downstream crates, allowing LLVM to have the body available for inlining even when not using fat LTO
    - However, for generic functions this needs to happen regardless, since it's how the compiler knows how to monomorphize them in a downstream crate.

So overall, there's typically not a need to include the attribute on generic code like most of itertools.

**Comment by errantmind** [comment]
That answers my question, thanks. I'll close this.
