### ISSUE TITLE
impl PeekingNext for &mut PeekingNext

### ISSUE THREAD

**Issue by ijackson** [rust-itertools/itertools#678]
Is there some reason we don't have this?
```
impl<I: PeekingNext> PeekingNext for &mut I { ... }
```

I can't thinkl of one and I found myself wanting it.  Should I prepare an MR?

**Comment by scottmcm** [comment]
Beware that `&mut` is fundamental, so this is a breaking change and will need a semver major version bump.  (I could have implemented `PeekingNext` for `&mut MyIterator`, which this would break.)

I doubt anyone *did*, but should probably take the bump just in case.

(This problem is why, sadly, we couldn't add `impl<E: Extend> Extend for &mut E` in `core`.)

**Comment by Philippe-Cholet** [comment]
It seems to me that #643 implements exactly this, and it was released in 0.11.0.
I really don't see why it [added](https://github.com/rust-itertools/itertools/pull/643/files#diff-1bd4359f7e7919a48889c2570b9c89a5313e71ae1b969ccd042b1ed980b9ea57R19) `Self: Sized` constraint thought.

**Comment by ijackson** [comment]
> It seems to me that #643 implements exactly this, and it was released in 0.11.0.

So it did, thanks.
